### ISSUE TITLE
typo issue

### ISSUE THREAD

**Issue by n3d4ti** [siw36/ansible-cloudflare-dns#1]
Seems to be need a typo fix in zone.yml file at line 77:
value: "{{ record.value }}" instead of value: "{{ record.type }}".

Also at line 80:
proxied: "{{ record.proxied }}" instead of proxied: "{{ item.proxied }}"

**Comment by siw36** [comment]
Sorry for the delay. I was not getting any notifications from Github. I reviewed your PR, approved and merged. Thanks for your contribution.
